sonata-project/SonataTranslationBundle

- Checker/TranslatableChecker.php
Reenables compatibility with php 5.3
> fixes issue #27

- Block/LocaleSwitcherBlockService.php
> Fix deprecated settings method on block service

- Resources/doc/index.rst
- Resources/doc/reference/advanced_configuration.rst
- Resources/doc/reference/installation.rst
- Resources/doc/reference/orm.rst
- Resources/doc/reference/phpcr.rst
sonata-project/SonataAdminBundle#3310
> streamline whole documentation and added advanced_configuration

- Resources/doc/reference/installation.rst
> Update TranslationBundle doc with the right bundle name

- Block/LocaleSwitcherBlockService.php
- EventListener/LocaleSwitcherListener.php
- Resources/config/listener.xml
- Resources/public/css/sonata-translation.css
- Resources/public/less/sonata-translation.less
- Resources/views/Block/block_locale_switcher.html.twig
> #66 : Feature : add locale switcher on show action

- Resources/doc/index.rst
- Resources/doc/reference/custom_action.rst
@OskarStark actually it just work without any changes in the code.
So this PR is just documentation. As I'm not a wonderful english writer would be great if you can read this.
I wait for this to be merge and I'll finish the doc improvement to close pending issues...
Thanks for your help
> #67 : Feature : add locale switcher on custom actions

- Resources/doc/reference/installation.rst
Fixes https://github.com/sonata-project/SonataTranslationBundle/issues/65 and also updates the docs to use the recommended default bundle installation guide.
> Improve installation docs

- Resources/doc/reference/custom_action.rst
> add missing quote sign

- .travis.yml
- composer.json
Subj; confirmed to work w/o further modifications.
> Updated composer to support 3.0 symfony version

- composer.json
add missing sonata admin bundle dependency and require only the needed
symfony components.
> Fixed necessary dependencies

- Block/LocaleSwitcherBlockService.php
- Resources/doc/reference/custom_action.rst
- Resources/views/Block/block_locale_switcher.html.twig
Add ability to pass additional route_parameters for locale_switcher_route on locale switcher block
> locale_switcher_route_parameters

- Resources/doc/reference/orm.rst
This looks like a copy/paste mistake
> Adapt title to the content below it

- composer.json
The suggest section is supposed to contain text explaining why pick a
suggested package.
> Move suggest constraints to conflict section

- .gitignore
I am targetting this branch, because this is a pedantic branch.
Related to: sonata-project/dev-kit#211
Remove plateform specific ignore entries from .gitignore file.
> Finalize .gitignore updates

- Resources/translations/SonataTranslationBundle.pl.xliff
I am targetting this branch, because it is BC.
```markdown
- Added Polish translation
```
Added Polish translation file.
> Add Polish translation

- Resources/config/config.yml
I am targetting this branch, because this is BC.
Removed blank line in config file
> removed blank line

- Resources/doc/reference/orm.rst
I am targeting this branch, because this is a doc fix.
Closes #159
> fixed headlines in docs

- Tests/AdminExtension/Knplabs/TranslatableAdminExtensionTest.php
- Tests/Checker/TranslatableCheckerForKnpTest.php
- Tests/Fixtures/Model/Knplabs/TranslatableEntity.php
- Tests/Fixtures/Model/Knplabs/TranslatableEntityTranslation.php
I am targeting this branch, because it adds tests.
It is related to the last comment of #117
> add tests for knplabs support

- Checker/TranslatableChecker.php
- phpunit.xml.dist
I am targeting this branch, because this is pedantic.
I think coverage is not calculated correctly, lets see
> Remove exceptions from phpunit whitelist

- src/Resources/translations/SonataTranslationBundle.ru.xliff
```markdown
- Added Russian translations
```
Added Russian translations.
> Added Russian translations

- composer.json
```markdown
- Compatibility with Symfony4
```
Remove direct dependency with framework bundle (only needed for test), and make Symfony dependencies explicit.
Also allow symfony4 to be installed
> Rework Symfony dependencies + SF4 compat

- composer.json
> Minor composer improvement

- src/Filter/TranslationFieldFilter.php
Make TranslationFieldFilter respect condition, fixes global search on translatable fields. Fixes #240
> Make TranslationFieldFilter respect condition

- composer.json
I am targeting this branch, because this is pedantic.
Fixes #245
Fixes the build
> Updated phpunit-bridge

- docs/reference/advanced_configuration.rst
- docs/reference/custom_action.rst
- docs/reference/global_locale_switcher.rst
- docs/reference/installation.rst
- docs/reference/orm.rst
- docs/reference/phpcr.rst
- use .yaml instead of .yml
- use App instead of AppBundle namespace
- fixed config paths
> [Docs] small changes

- .gitattributes
- .php_cs.dist
- .travis/before_script_test.sh
- CONTRIBUTING.md
- composer.json
- docs/conf.py
- src/Filter/TranslationFieldFilter.php
> Manual merge

- src/Block/LocaleSwitcherBlockService.php
- src/DependencyInjection/Configuration.php
- src/DependencyInjection/SonataTranslationExtension.php
- src/Resources/config/block.xml
- src/Resources/views/Block/block_locale_switcher.html.twig
- src/Twig/Extension/SonataTranslationExtension.php
- tests/DependencyInjection/SonataTranslationExtensionTest.php
This pull request removes the country flags from the language switcher and replaces them with the (translated) locale names. 
There is no one-to-one relation between a locale and a country. A language can be spoken in multiple countries and one country can speak multiple languages.
I am targeting 2.x because this change is backwards compatible.
Closes #133
```markdown
- Feature flag to either keep using country flags or show locale names in language switcher
- Replace country flags with locale names in language switcher
```
> Display locale names instead of flags in language switcher

- docs/reference/installation.rst
- docs/reference/orm.rst
- src/DependencyInjection/Configuration.php
- src/DependencyInjection/SonataTranslationExtension.php
- src/Enum/TranslationFilterMode.php
- src/Filter/TranslationFieldFilter.php
- src/Resources/config/service_orm.xml
- tests/Fixtures/Traits/ORM/Knplabs/Article.php
- tests/Fixtures/Traits/ORM/Knplabs/ArticleTranslation.php
- tests/Model/KnplabsTest.php
- tests/Traits/GedmoOrmTest.php
- tests/Traits/KnplabsOrmTest.php
I am targeting this branch, because the `TranslationFieldFilter` was not working when using **KnpLabs**. The query made in the filter was not handling the database schema of **KnpLabs**. This PR adds support for both of these providers.
It adds a global option for the bundle `default_filter_mode`, which can either be `gedmo` or `knplabs`. And it adds a `filter_mode` options to the field filter, to allow customizing it on a per-field basis.
I could not find a related issue
```markdown
- Added a global option `default_filter_mode` to change every filter mode
- Added `filter_mode` option for `TranslationFieldFilter` to change the filtering mode based on the provider (either `knplabs` or `gedmo`)
```
> Support for KNP when using `TranslationFieldFilter`

- composer.json
I am targeting this branch, because it its BC-~~break~~.
```markdown
- Removed `SonataCoreBundle` 
```
> Drop SonataCoreBundle

- src/Resources/translations/SonataTranslationBundle.nl.xliff
This PR adds a Dutch translation.
I am targeting this branch, because it's backwards compatible.
```markdown
- Dutch translation
```
> Add Dutch translation

- .github/workflows/test.yaml
- composer.json
- src/Admin/Extension/AbstractTranslatableAdminExtension.php
- src/Filter/TranslationFieldFilter.php
Allows `sonata-project/admin-bundle` 4.x
Allows `sonata-project/doctrine-orm-admin-bundle` 4.x
> Allow to install latest version of sonata packages

- src/Admin/Extension/Gedmo/TranslatableAdminExtension.php
- src/Admin/Extension/Knplabs/TranslatableAdminExtension.php
- src/Admin/Extension/Phpcr/TranslatableAdminExtension.php
- src/Block/LocaleSwitcherBlockService.php
- src/Checker/TranslatableChecker.php
- src/DependencyInjection/Compiler/AdminExtensionCompilerPass.php
- src/DependencyInjection/Compiler/GlobalVariablesCompilerPass.php
- src/DependencyInjection/Configuration.php
- src/DependencyInjection/SonataTranslationExtension.php
- src/EventListener/LocaleSwitcherListener.php
- src/SonataTranslationBundle.php
- src/Twig/Extension/SonataTranslationExtension.php
Following the idea to make classes final.
```markdown
- Mark classes as final
```
> Mark classes as final

- composer.json
- phpstan-baseline.neon
- src/Admin/Extension/AbstractTranslatableAdminExtension.php
- src/Admin/Extension/Gedmo/TranslatableAdminExtension.php
- src/Admin/Extension/Phpcr/TranslatableAdminExtension.php
- src/Resources/config/service_gedmo.xml
- src/Resources/config/service_knplabs.xml
- src/Resources/config/service_phpcr.xml
- tests/Admin/Extension/AbstractTranslatableAdminExtensionTest.php
- tests/Admin/Extension/Gedmo/DeprecatedTranslatableAdminExtensionTest.php
- tests/Admin/Extension/Gedmo/TranslatableAdminExtensionTest.php
- tests/Admin/Extension/Knplabs/TranslatableAdminExtensionTest.php
- tests/Traits/DoctrineOrmTestCase.php
- tests/Traits/GedmoOrmTest.php
- tests/Traits/KnplabsOrmTest.php
This PR adds some deprecations to remove Container dependency in Admin extensions.
```markdown
- Deprecated `Sonata\TranslationBundle\Test\DoctrineOrmTestCase`.
- Deprecated constructing `AbstractTranslatableAdminExtension` without the default translation locale.
- Deprecated protected `AbstractTranslatableAdminExtension::getContainer()` method.
- Deprecated protected `AbstractTranslatableAdminExtension::getTranslationLocales()` method.
- Deprecated protected `AbstractTranslatableAdminExtension::getDefaultTranslationLocale()` method.
- Deprecated constructing `Sonata\TranslationBundle\Admin\Extension\Gedmo\TranslatableAdminExtension` without an instance of `TranslatableListener` and `ManagerRegistry`.
```
> Add some deprecations

- src/Resources/translations/SonataTranslationBundle.pt.xliff
Added translations to Portuguese
Added Portuguese to SonataTranslationBundle
I am targeting this branch, because this is an addiction that is backwards compatible.
```markdown
- Added `SonataTranslationBundle.pt.xliff` to support Portuguese(Portugal) language.
```
> Add pt language

- src/Action/SwitchLocaleAction.php
- src/Admin/Extension/AbstractTranslatableAdminExtension.php
- src/Admin/Extension/Gedmo/TranslatableAdminExtension.php
- src/Admin/Extension/Knplabs/TranslatableAdminExtension.php
- src/Admin/Extension/Phpcr/TranslatableAdminExtension.php
- src/Block/LocaleSwitcherBlockService.php
- src/Checker/TranslatableChecker.php
- src/DependencyInjection/Compiler/AdminExtensionCompilerPass.php
- src/DependencyInjection/Compiler/GlobalVariablesCompilerPass.php
- src/DependencyInjection/Configuration.php
- src/DependencyInjection/SonataTranslationExtension.php
- src/EventListener/LocaleSwitcherListener.php
- src/EventSubscriber/LocaleSubscriber.php
- src/EventSubscriber/UserLocaleSubscriber.php
- src/Filter/TranslationFieldFilter.php
- src/Model/AbstractTranslatable.php
- src/Model/Gedmo/AbstractPersonalTranslatable.php
- src/Model/TranslatableInterface.php
- src/SonataTranslationBundle.php
- src/Traits/Gedmo/PersonalTranslatableTrait.php
- src/Twig/Extension/IntlExtension.php
- tests/Fixtures/Model/Knplabs/TranslatableEntity.php
I am targeting this branch, because these changes respect BC.
> Add type declarations

- composer.json
- phpstan-baseline.neon
- phpstan.neon.dist
- psalm-baseline.xml
- psalm.xml
- src/Admin/Extension/AbstractTranslatableAdminExtension.php
- src/Admin/Extension/Gedmo/TranslatableAdminExtension.php
- src/Admin/Extension/Knplabs/TranslatableAdminExtension.php
- src/Admin/Extension/Phpcr/TranslatableAdminExtension.php
- src/Block/LocaleSwitcherBlockService.php
- src/Checker/TranslatableChecker.php
- src/DependencyInjection/Compiler/AdminExtensionCompilerPass.php
- src/DependencyInjection/Compiler/GlobalVariablesCompilerPass.php
- src/DependencyInjection/SonataTranslationExtension.php
- src/Model/Gedmo/AbstractPersonalTranslation.php
- src/SonataTranslationBundle.php
- src/Twig/Extension/SonataTranslationExtension.php
This raises from 1 to 6 the phpstan level and from 6 to 4 the psalm one.
> Psalm phpstan levels

- composer.json
- phpstan-baseline.neon
- phpstan.neon.dist
- psalm-baseline.xml
- psalm.xml
- src/Admin/Extension/AbstractTranslatableAdminExtension.php
- src/Admin/Extension/Gedmo/TranslatableAdminExtension.php
- src/DependencyInjection/SonataTranslationExtension.php
- src/EventSubscriber/UserLocaleSubscriber.php
- src/Filter/TranslationFieldFilter.php
- src/Traits/Gedmo/PersonalTranslatableTrait.php
- src/Traits/Gedmo/TranslatableTrait.php
- src/Traits/TranslatableTrait.php
- tests/Admin/Extension/AbstractTranslatableAdminExtensionTest.php
- tests/Admin/Extension/Gedmo/DeprecatedTranslatableAdminExtensionTest.php
- tests/Admin/Extension/Gedmo/TranslatableAdminExtensionTest.php
- tests/Admin/Extension/Knplabs/TranslatableAdminExtensionTest.php
- tests/EventSubscriber/LocalizedUser.php
- tests/EventSubscriber/User.php
- tests/EventSubscriber/UserLocaleSubscriberTest.php
- tests/Fixtures/Model/Knplabs/TranslatableEntity.php
- tests/Fixtures/Model/Knplabs/TranslatableEntityTranslation.php
- tests/Fixtures/Traits/ModelPersonalTranslatable.php
- tests/Fixtures/Traits/ORM/ArticlePersonalTranslatable.php
- tests/Fixtures/Traits/ORM/ArticlePersonalTranslation.php
- tests/Fixtures/Traits/ORM/Knplabs/Article.php
- tests/Fixtures/Traits/ORM/Knplabs/ArticleTranslation.php
- tests/Resources/XliffTest.php
- tests/Traits/GedmoOrmTest.php
- tests/Traits/KnplabsOrmTest.php
The ignored errors are going to be removed in the next major version.
> Raise Psalm to error level 3 and add tests directory

- src/Filter/TranslationFieldFilter.php
Related to https://github.com/sonata-project/SonataAdminBundle/pull/6636
The phpstan error has been fixed in https://github.com/doctrine/orm/pull/8386, but there is no release yet.
> Change variable names to be in sync with the parent ones

- composer.json
- src/Admin/Extension/AbstractTranslatableAdminExtension.php
- src/Admin/Extension/Gedmo/TranslatableAdminExtension.php
- src/Admin/Extension/Knplabs/TranslatableAdminExtension.php
- src/Admin/Extension/Phpcr/TranslatableAdminExtension.php
- src/Model/TranslatableInterface.php
- tests/Admin/Extension/AbstractTranslatableAdminExtensionTest.php
- tests/Admin/Extension/Gedmo/DeprecatedTranslatableAdminExtensionTest.php
- tests/Admin/Extension/Gedmo/TranslatableAdminExtensionTest.php
- tests/Admin/Extension/Knplabs/TranslatableAdminExtensionTest.php
The user shouldn't be affected by these changes
> Fix static analysis issues

- UPGRADE-2.x.md
- composer.json
- docs/reference/installation.rst
- phpstan-baseline.neon
- phpstan.neon.dist
- src/Checker/TranslatableChecker.php
- src/DependencyInjection/Configuration.php
- src/DependencyInjection/SonataTranslationExtension.php
- src/Model/Gedmo/AbstractPersonalTranslatable.php
- src/Resources/config/service_gedmo.xml
- src/Traits/Gedmo/PersonalTranslatableTrait.php
- tests/DependencyInjection/ConfigurationTest.php
- tests/DependencyInjection/SonataTranslationExtensionTest.php
- tests/Resources/XliffTest.php
Ref: https://github.com/sonata-project/SonataTranslationBundle/pull/453#issuecomment-785344620
Instead of relying on the bundle, a `sonata_translation.gedmo.translatable_listener_service` option has been added to the configuration so the user must specify the translatable listener service name when using gedmo (allowing to use another bundle or only the package). 
```markdown
- Added `sonata_translation.gedmo.translatable_listener_service` option to specify the translatable listener service name.
- Deprecated not setting `sonata_translation.gedmo.translatable_listener_service` option when using gedmo.
```
> Remove stof/doctrine-extensions-bundle dependency

- .github/workflows/test.yaml
- composer.json
```markdown
- Add support for PHP 8.0
```
> Allow support PHP 8.0

- psalm-baseline.xml
- psalm.xml
- src/DependencyInjection/Configuration.php
The issue is with the `->end()` call on a possible null value.
> Ignore psalm issues

- composer.json
- tests/App/Admin/GedmoCategoryAdmin.php
- tests/App/AppKernel.php
- tests/App/DataFixtures/GedmoCategoryFixtures.php
- tests/App/Entity/GedmoCategory.php
- tests/App/config/config_v4.yml
- tests/App/config/config_v5.yml
- tests/App/config/routes.yaml
- tests/App/config/security_v4.yml
- tests/App/config/security_v5.yml
- tests/App/config/services.php
- tests/Checker/TranslatableCheckerForKnpTest.php
- tests/Functional/GedmoCRUDTest.php
- tests/custom_bootstrap.php
I added code for Symfony 5 since it has been copied from another bundle and this would ease merging it with `3.x`.
> Add functional tests for Gedmo

- docs/reference/orm.rst
Follow-up of https://github.com/sonata-project/SonataTranslationBundle/pull/537
> Remove references to abstract classes and traits in docs
