sonata-project/SonataTranslationBundle

Resources/public/css/sonata-translation.css, Resources/public/less/sonata-translation.less
Hello,
i'm using your assets with grunt-csslint then standard rules (and css good practices) says that 0 values must not have unit.
NB : css was been redo with grunt-less (lessc inside)
=> [Fix] csslint standard rules disallow "0px" syntax on css files.

Checker/TranslatableChecker.php
`Sonata\TranslationBundle\Traits\Gedmo\PersonalTranslatable` uses `Sonata\TranslationBundle\Traits\Translatable`, but `class_uses` will only return `PersonalTranslatable`, although it indirectly uses `Translatable`. I suggest also checking for `PersonalTranslatable` in `TranslatableChecker`. Maybe the traits could even be made configurable like the interfaces or the models.
=> Also check for PersonalTranslatable

Admin/Extension/Gedmo/TranslatableAdminExtension.php, Resources/config/service_gedmo.xml
The service `stof_doctrine_extensions.listener.translatable` is no longer available as a public service and can't be retrieved by name anymore.
It is now injected as constructor parameter in `Sonata\TranslationBundle\Admin\Extension\Gedmo\TranslatableAdminExtension` using the alias
`sonata_translation.listener.translatable`.
Fixes #58
@nicolas-bastien
=> Add TranslatableListener constructor parameter to Gedmo\TranslatableAdminExtension service

Admin/Extension/Phpcr/TranslatableAdminExtension.php
Currently, it is impossible to add a new translation of a document using the admin fields. With this patch, adding new translations is possible.
Fixes https://github.com/symfony-cmf/cmf-sandbox/issues/323
=> [PHPCR] Make it possible to create new languages of a document

Admin/Extension/Gedmo/TranslatableAdminExtension.php, CHANGELOG.md
there has been a BC break after 1.0.1 that has not been released yet.
=> make gedmo extension changes backwards compatible

Block/LocaleSwitcherBlockService.php
fix #55
fix https://github.com/symfony-cmf/cmf-sandbox/issues/325
/cc @WouterJ i think this is the way to work with both versions
=> make block settings work with older versions of sonata block bundle too

composer.json
```markdown
- Fix wrong conflict rule for `doctrine-orm-admin-bundle`
```
Should begin at 3.0, not 2.0.
ping @alexndlm @greg0ire
=> Fix wrong conflict rule for doctrine-orm-admin-bundle

composer.json
As I already tried to explain, this bundle **does not depend on SonataDoctrinePhpcrOdmAdminBundle**. It makes absolutely no sense to set up conflict rules for this package.
A proof that this bundle doesn't use anything from that bundle: https://github.com/sonata-project/SonataTranslationBundle/search?utf8=%E2%9C%93&q=DoctrinePhpcr
=> Remove doctrine phpcr admin conflict

composer.json
As requested in https://github.com/sonata-project/SonataTranslationBundle/pull/110#issuecomment-224930807 I also added a Doctrine PHPCR-ODM suggestion and conflict, because that's what's actually integrated in this bundle.
The conflict now is `>=2.0`, although multilang is such a fundamental feature of the PHPCR ODM that I don't expect much BC breaks in it. So the current code would probably work on 2.0 as well, but I guess you prefer to be very explicit about the supported versions.
=> Remove adapter bundles from the composer.json

composer.json
This bundle currently supports Doctrine PHPCR ODM 2. This is needed to get the CMF sandbox installable again /cc @dbu
=> Bump the PHPCR ODM conflict

Resources/doc/reference/installation.rst
Removing Composer version in order to force it choose latest version. according to [issuecomment-239639169](https://github.com/sonata-project/SonataTranslationBundle/pull/120#issuecomment-239639169) by @dbu
=> translation-bundle version-neutral composer cmd

Tests/Checker/TranslatableCheckerTest.php, Tests/Model/GedmoTest.php, Tests/Resources/XliffTest.php, Tests/Traits/GedmoTest.php
I am targetting this branch, because it is backwards compatible minor fix
```markdown
fix tests namespace
```
Changed namespace for test classes from `Sonata\AdminBundle\Tests` to `Sonata\TranslationBundle\Tests`
=> fix tests namespace

Checker/TranslatableChecker.php, Resources/doc/reference/orm.rst, Tests/Checker/TranslatableCheckerTest.php, Tests/Fixtures/Model/ModelCustomTranslatable.php, Tests/Fixtures/Model/ModelPersonalTranslatable.php, Tests/Fixtures/Model/ModelPersonalTranslation.php, Tests/Fixtures/Model/ModelTranslatable.php, Tests/Fixtures/Model/ModelUsingTraitTranslatable.php, Tests/Fixtures/Traits/ModelPersonalTranslatable.php, Tests/Fixtures/Traits/ModelPersonalTranslation.php, Tests/Fixtures/Traits/ModelTranslatable.php, Tests/Model/GedmoTest.php, Tests/Traits/GedmoTest.php, Traits/Gedmo/PersonalTranslatable.php, Traits/Gedmo/PersonalTranslatableTrait.php, Traits/TranslatableTrait.php
I am targetting this branch, because this is BC.
Closes #123
```markdown
- deprecate `Translatable` in favor of `TranslatableTrait`
- deprecate `PersonalTranslatable` in favor of `PersonalTranslatableTrait`
```
According to [symfony coding standards](https://symfony.com/doc/current/contributing/code/standards.html#naming-conventions), all traits should have a `*Trait` suffix.
=> Deprecate old trait names

Resources/views/Block/block_locale_switcher.html.twig
I am targetting this branch, because it is fix for 2.x.
```markdown
- Display flags for locales with country code
```
Locale Switcher Block does not display flag icons for locales with country codes, i.e.: pt_BR, en_US. There are no such images, so user see 404 instead. This solution just take last 2 characters from locale and display proper icon. It will be:
`pt.png` for `pt`
`br.png` for `pt_BR`
`us.png` for `en_US`
etc.
=> Display flags for locales with country code

Test/DoctrineOrmTestCase.php, Tests/Fixtures/Traits/ORM/ArticlePersonalTranslatable.php, Tests/Fixtures/Traits/ORM/ArticlePersonalTranslation.php, Tests/Traits/GedmoOrmTest.php, Traits/Gedmo/PersonalTranslatableTrait.php, Traits/Gedmo/TranslatableTrait.php
I am targetting this branch, because it is a bug fix for 2.x
```markdown
- fix missing locale annotation for Gedmo trait
```
`\Traits\Gedmo\PersonalTranslatableTrait` should use new `\Traits\Gedmo\TranslatableTrait` with `@Gedmo\Locale` annotation (same as `\Model\Gedmo\AbstractTranslatable` class). This fix `$entity->setLocale('XX')` mechanic if entity use traits.
=> fix missing locale annotation for Gedmo trait

UPGRADE-2.x.md
I am targetting this branch, because this is just a doc update.
Fixes #124
Adds the missing `UPGRADE-2.x` docs for trait deprecation.
=> Added missing upgrade notes for traits

Admin/Extension/AbstractTranslatableAdminExtension.php, composer.json
I am targetting this branch, because it is BC.
```markdown
- Use `AbstractAdminExtension` instead of deprecated `AdminExtension`
```
=> Fix deprecated AdminExtension class usage

Admin/Extension/Gedmo/TranslatableAdminExtension.php, EventListener/LocaleSwitcherListener.php, Filter/TranslationFieldFilter.php, Resources/config/listener.xml, Resources/config/service.xml, Resources/doc/reference/orm.rst, Resources/public/css/sonata-translation.css, Resources/public/less/sonata-translation.less, Resources/views/Block/block_locale_switcher.html.twig, Tests/Traits/GedmoOrmTest.php
I am targetting this branch, because it is BC.
fix #81, fix #83
continuation of #83, #84, #119
```markdown
- [gedmo translations] Added content language switcher to lists
- [gedmo translations] Added available translations filter 
```
From original PR:
> In the configureQuery, with the translatable listener the locale is changed for Doctrine and data are translated on the list.
> translationFieldFilter is a callback method to use on doctrine_orm_callback filter to filter on field and on its translation.
I merged conflicts, fixed null exception in block template and added documentation for `translationFieldFilter`.
=> allow to switch content language on list and filter by language (continued)

Block/LocaleSwitcherBlockService.php, composer.json
I am targetting this branch, because this is BC.
```markdown
- use `Sonata\BlockBundle\Block\Service\AbstractBlockService` instead of deprecated `Sonata\BlockBundle\Block\BaseBlockService` in `LocaleSwitcherBlockService`
```
=> use Sonata\BlockBundle\Block\Service\AbstractBlockService instead of deprecated Sonata\BlockBundle\Block\BaseBlockService

Resources/doc/reference/orm.rst
I am targeting this branch, because it is documentation fix.
```markdown
updated documentation
```
As @greg0ire noticed in https://github.com/sonata-project/SonataTranslationBundle/issues/154#issuecomment-285636156 the numbering in orm doc could be improved. I removed manual numbers and fixed hierarchy.
=> Fix section headers in orm doc

Admin/Extension/Phpcr/TranslatableAdminExtension.php, Resources/config/service_phpcr.xml
I am targeting this branch, because it's a BC new feature.
```markdown
- Added phpcr lists translations
```
Hi, I just installed this bundle to translate phpcr elements, and I noticed the lists are not correctly translated.
I hope that's the correct way to achieve this !
=> Translate phpcr lists

Tests/DependencyInjection/SonataTranslationExtensionTest.php, composer.json
I am targetting this branch, because this is BC.
```markdown
- support of Twig 2.0
```
=> Twig 2.0 compatibility

composer.json
I am targeting this branch, because it is BC tests improvement.
No need, bacause it is affects only dev packages.
Travis skip 4 unit tests because no dependency.
```
............SSSS..                                                18 / 18 (100%)
Time: 3.1 seconds, Memory: 22.00MB
OK, but incomplete, skipped, or risky tests!
Tests: 18, Assertions: 36, Skipped: 4.
```
I added ~~additional target for Travis~~ "sonata-project/doctrine-orm-admin-bundle" to `composer.json` dev packages. It is needed to test `TranslationFieldFilter` (which extends `Sonata\DoctrineORMAdminBundle\Filter\Filter`) and Personal Translation.
=> Allow to test TranslationFieldFilter and ORM Personal Translation

Admin/Extension/AbstractTranslatableAdminExtension.php, Tests/AdminExtension/Knplabs/TranslatableAdminExtensionTest.php
I am targeting this branch, because it is bugfix.
Closes #164
```markdown
- Fix RuntimeException in sonata:admin:explain command
```
RuntimeException is thrown in `sonata:admin:explain` command and output is truncated.
=> Fix RuntimeException in sonata:admin:explain command

Filter/TranslationFieldFilter.php, composer.json
```markdown
- Removed usage of old form type aliases
- support for old versions of php and Symfony
```
=> Drop old versions of php/sf

Tests/Checker/TranslatableCheckerForKnpTest.php, Tests/Checker/TranslatableCheckerTest.php, Tests/Model/GedmoTest.php, Tests/Traits/GedmoTest.php
Removed compatibility with PHPUnit 4. Fixes: https://github.com/sebastianbergmann/phpunit/issues/2809
=> Drop PHPUnit 4

composer.json
Old versions seem to make Composer hang.
This is a test for this PR: https://github.com/sonata-project/SonataTranslationBundle/pull/200
=> Bump composer dependencies

composer.json, docs/reference/installation.rst, src/Block/LocaleSwitcherBlockService.php, src/Resources/config/block.xml
I am targeting this branch, because this is a patch.
```markdown
- Switch all templates references to Twig namespaced syntax
- Switch from templating service to sonata.templating
```
This PR is a part of a big plan of decoupling sonata-project bundles from Templating Component. See sonata-project/dev-kit#380 for details
=> Decouple from Templating Component, Stage 1

src/Resources/public/css/sonata-translation.css
```markdown
- language switcher does not have the same style in modal
```
Before:
After:
Language switcher did not have the same style inside of modal as rest of app, this fixes it.
=> Add style for locale switcher in modal

docs/reference/installation.rst
I am targeting this branch, because I am improving docs.
Adding asset to `sonata_admin` config looks a lot easier to me than extending the template and replacing it.
=> Improve docs for importing css

src/DependencyInjection/SonataTranslationExtension.php, tests/DependencyInjection/SonataTranslationExtensionTest.php, tests/Model/GedmoTest.php, tests/Traits/GedmoTest.php
```markdown
- Added check if translatable checker service exists
```
`SonataDoctrineORMBundle` is optional dependency for this bundle. And if `SonataDoctrineORMBundle` was not installed, after installation there would be a error during `cache:clear` command:
> You have requested a non-existent service "sonata_translation.checker.translatable"
With this PR this error will not appear with the following default configuration (recipe =)
```yaml
sonata_admin:
assets:
extra_stylesheets:
- bundles/sonatatranslation/css/sonata-translation.css
sonata_block:
blocks:
sonata_translation.block.locale_switcher: ~
sonata_translation:
locales: [en]
default_locale: en
#gedmo:
#knplabs:
```
=> Check if 'sonata_translation.checker.translatable' service exists

src/DependencyInjection/Compiler/AdminExtensionCompilerPass.php
Currently when creating an admin with no entity (`~` as argument), the [get_class](https://github.com/storefront-bvba/SonataTranslationBundle/blob/af09eb0f51162ae05c5365835869f4ddfeed9a98/src/DependencyInjection/Compiler/AdminExtensionCompilerPass.php#L36) throws `class_exists() expects parameter 1 to be string`. To overcome this I would first check if there's a model class and after that check if it exists. 
An other solution is to provide an empty string as argument but that's a bit hacky.
I am targeting this branch, because it's a small improvement which AFAIK wont break a thing.
```markdown
- Admin without entity shouldn't be restricted
```
=> Make it possible to create an admin without entity

src/EventSubscriber/UserLocaleSubscriber.php, tests/EventSubscriber/LocalizedUser.php, tests/EventSubscriber/UserLocaleSubscriberTest.php
I am targeting this branch, because this is a bug fix.
Closes #297 
```markdown
Check if method getLocale exists before to use it in UserLocaleListener
```
=> Check if method getLocale exists before to use it

src/Admin/Extension/Gedmo/TranslatableAdminExtension.php
When using multiple entity managers with different entities in their chains, this extension always fetched the default entity manager from the registry instead of the one for the given object
I am targeting this branch, because it is a BC bug fix.
```markdown
Fixed issue caused by always using the default entity manager
```
=> Fixed issue caused by always using the default entity manager

composer.json, src/Checker/TranslatableChecker.php
This is the same thing as https://github.com/sonata-project/SonataAdminBundle/pull/5733, dropping support of Symfony < 3.4 and >= 4, < 4.2
I am targeting this branch, because these changes respect BC.
```markdown
- Support for Symfony < 3.4
- Support for Symfony >= 4, < 4.2
```
=> Dropping support for symfony < 3.4

docs/reference/orm.rst, docs/reference/phpcr.rst
While reading the Sonata Translation docs I noticed some bugs like missing backslashes in FQCN's. I also ran the spinx linkcheck to fix some links.
I am targeting this branch, because it's just docs.
Not needed for doc changes.
=> Documentation: styling, grammar and links improved

composer.json, src/Block/LocaleSwitcherBlockService.php, src/DependencyInjection/Configuration.php, src/Model/Gedmo/AbstractPersonalTranslatable.php, src/Resources/config/block.xml, src/Traits/Gedmo/PersonalTranslatableTrait.php, src/Twig/Extension/SonataTranslationExtension.php, tests/Action/SwitchLocaleActionTest.php, tests/AdminExtension/Knplabs/TranslatableAdminExtensionTest.php, tests/Checker/TranslatableCheckerForKnpTest.php, tests/Checker/TranslatableCheckerTest.php, tests/DependencyInjection/SonataTranslationExtensionTest.php, tests/EventSubscriber/LocaleSubscriberTest.php, tests/EventSubscriber/LocalizedUser.php, tests/EventSubscriber/UserLocaleSubscriberTest.php, tests/Fixtures/Traits/ORM/Knplabs/Article.php, tests/Fixtures/Traits/ORM/Knplabs/ArticleTranslation.php, tests/Model/GedmoTest.php, tests/Model/KnplabsTest.php, tests/Resources/XliffTest.php, tests/Traits/GedmoOrmTest.php, tests/Traits/GedmoTest.php
Before solving https://github.com/sonata-project/SonataTranslationBundle/issues/335, dropping Symfony < 4.3 and some tests clean up 
```markdown
- Support of Symfony < 4.3
```
=> Drop support of Symfony < 4.3

src/DependencyInjection/SonataTranslationExtension.php, src/Resources/config/twig_intl.xml, src/Resources/views/standard_layout.html.twig, src/Twig/Extension/IntlExtension.php, tests/DependencyInjection/SonataTranslationExtensionTest.php, tests/Twig/Extension/Fixtures/language_name.test, tests/Twig/Extension/IntlExtensionTest.php
`language_name` was added, but it needed `twig/intl-extra`. I added `sonata_language_name` to avoid conflicts.
Closes #335
```markdown
- Added `sonata_language_name` Twig filter
- Use of undefined filter `language_name`
```
=> Add sonata_language_name twig filter

src/Resources/views/Block/block_locale_switcher.html.twig
This PR fixes the following deprecation notice:
> The spaceless tag in "@SonataTranslation/Block/block_locale_switcher.html.twig" at line 17 is deprecated since Twig 2.7, use the "spaceless" filter with the "apply" tag instead.
I am targeting this branch, because Twig 2.12 is the minimum required version of this branch.
```markdown
- Deprecation notice caused by use of spaceless tag in block_locale_switcher.html.twig.
```
=> Replace usage of deprecated spaceless Twig tag with apply spaceless

src/Resources/views/Block/block_locale_switcher.html.twig
I noticed the following deprecation message in my logs:
> Passing null as argument 1 for Sonata\DoctrineORMAdminBundle\Model\ModelManager::getNormalizedIdentifier() is deprecated since sonata-project/doctrine-orm-admin-bundle 3.20 and will be not allowed in version 4.0.
It appeared that block_locale_switcher.html.twig calls `admin.id(object)` on list pages, where object is null. I moved some code around to calculate the id only once and only if there is an object.
I also moved code that set a default value for the variable `locale_switcher_route` to outside the loop. This seems more appropriate.
I am targeting this branch, because it is a backwards compatible change.
```markdown
- Deprecation notice about ModelManager::getNormalizedIdentifier() on list pages.
```
=> Do not invoke admin.id() with null argument

composer.json
Some bundles like: NotificationBundle, DoctrineORMAdminBundle, PageBundle, SeoBundle, UserBundle using Symfony v4.4. To avoid situation like [here](https://github.com/sonata-project/SonataPageBundle/issues/1168#issuecomment-655587405) some bundles like this must bump Symfony < 4.4 too.
I am targeting this branch, because this change respect BC.
```markdown
- Support for PHP < 7.2
- Support for Symfony < 4.4
```
=> Bump Symfony < 4.4 and PHP < 7.2

composer.json
This PR enables Twig 3 in composer.json. There seem to be no further required changes.
I am targeting this branch, because this is a backwards compatible change.
```markdown
- Twig 3 compatibility.
```
=> Add support for Twig 3

src/EventSubscriber/UserLocaleSubscriber.php, src/Resources/config/service_locale_switcher.xml, tests/EventSubscriber/UserLocaleSubscriberTest.php
Update `UserLocaleSubscriber::onInteractiveLogin()` in order to avoid starting the session.
I am targeting this branch, because this change respects BC.
```markdown
- Fixed starting the session in `UserLocaleSubscriber::onInteractiveLogin()` when there is no previous session.
```
=> Update `UserLocaleSubscriber::onInteractiveLogin()` in order to avoid starting the session

UPGRADE-2.x.md, composer.json, src/Block/LocaleSwitcherBlockService.php, src/Resources/config/block.xml, tests/Block/LocaleSwitcherBlockServiceTest.php
I am targeting this branch, because it would be nice to have support of BlockBundle 4.
```markdown
- Add support for SonataBlockBundle 4.0
```
=> Add support for BlockBundle 4

.github/workflows/qa.yaml, composer.json, phpstan.neon.dist, src/Admin/Extension/AbstractTranslatableAdminExtension.php
I've added some packages to require-dev as they were errors because classes didn't exist.
=> Add PHPStan check

src/EventSubscriber/LocaleSubscriber.php
It was deprecated [in symfony 4.3](https://github.com/symfony/symfony/blob/4.4/UPGRADE-4.3.md#httpkernel).
I am targeting this branch, because this change is BC.
```markdown
- Replaced deprecated `GetResponseEvent` with `RequestEvent`.
```
=> Replace deprecated GetResponseEvent with RequestEvent

composer.json, phpstan-baseline.neon, phpstan.neon.dist, psalm-baseline.xml, tests/Fixtures/Model/Knplabs/TranslatableEntity.php, tests/Fixtures/Model/Knplabs/TranslatableEntityTranslation.php, tests/Fixtures/Traits/ORM/Knplabs/AbstractArticleTranslation.php, tests/Fixtures/Traits/ORM/Knplabs/ArticleTranslation.php
Allows to install knplabs/doctrine-behaviors 2, apparently it introduced some interfaces.
```markdown
- Added support for `knplabs/doctrine-behaviors` 2.
```
=> Allow knplabs/doctrine-behaviors 2

composer.json, phpstan.neon.dist, psalm-baseline.xml, psalm.xml
Pedantic ; solve https://github.com/sonata-project/SonataTranslationBundle/pull/418#discussion_r521906888
To use the psalm phpunit plugin without requiring `phpunit/phpunit`, it required the last version of the plugin, which is only compatible with psalm 4. But the psalm doctrine plugin is currently not compatible with psalm 4.
=> Use Psalm with symfony phpunit bridge

composer.json, phpstan.neon.dist, tests/Fixtures/Model/Knplabs/TranslatableEntity.php, tests/Fixtures/Model/Knplabs/TranslatableEntityTranslation.php, tests/Fixtures/Traits/ORM/Knplabs/ArticleTranslation.php
`kplabs/doctrine-behaviours` 2.0 was release more than one year ago: https://github.com/KnpLabs/DoctrineBehaviors/releases/tag/v2.0.0
`gedmo/doctrine-extensions` 3.0 was released 7 months ago: https://github.com/doctrine-extensions/DoctrineExtensions/releases/tag/v3.0.0 IMO we can also drop support for 2.x.
```markdown
- Removed support for `knplabs/doctrine-behaviors` < 2.0
- Removed support for `doctrine/persistence` < 2.0
```
=> Drop support of knplabs/doctrine-behaviors <2.0

src/DependencyInjection/SonataTranslationExtension.php, tests/DependencyInjection/SonataTranslationExtensionTest.php
The argument passed to the `setAnnotationReader` method was a string instead of a reference to a service.
I am targeting this branch, because this is a bugfix.
```markdown
- Fixed registering `sonata_translation.listener.translatable` when no `translatable_listener_service` is defined
```
=> Fix service reference

src/Admin/Extension/AbstractTranslatableAdminExtension.php, tests/Admin/Extension/AbstractTranslatableAdminExtensionTest.php
There was this code:
```php
if ($admin->hasRequest()) {
$this->translatableLocale = (string) $admin->getRequest()->get(self::TRANSLATABLE_LOCALE_PARAMETER);
}
if (null === $this->translatableLocale) {
$this->translatableLocale = $this->defaultTranslationLocale;
}
```
if there was request, but no parameter, `$this->translatableLocale` was set to an empty string instead of the default locale.
I am targeting this branch, because the casting was introduced in this branch.
=> Set locale properly from the admin

src/Admin/Extension/Knplabs/TranslatableAdminExtension.php
Since the minimum version of knplabs/doctrine-behaviors is 2.0 in this branch, the model should implement TranslationInterface.
=> Check against interface

composer.json
It is used in https://github.com/sonata-project/SonataTranslationBundle/blob/a7e5eb022f6b915ef878e3ae3a54b17c55e56356/src/Twig/Extension/IntlExtension.php#L16-L17
I've labeled as _pedantic_ since there is no problem using it with Symfony 4 (`symfony/form` requires it).
=> Explicitly require symfony/intl

UPGRADE-2.x.md, src/Checker/TranslatableChecker.php, src/Model/AbstractTranslatable.php, src/Model/Gedmo/AbstractPersonalTranslatable.php, src/Model/Gedmo/AbstractPersonalTranslation.php, src/Model/Gedmo/AbstractTranslatable.php, src/Traits/Gedmo/PersonalTranslatableTrait.php, src/Traits/Gedmo/TranslatableTrait.php, src/Traits/TranslatableTrait.php, tests/Checker/TranslatableCheckerTest.php, tests/Fixtures/Model/ModelUsingTraitTranslatable.php
This bundle is supposed to handle the translation of models used in admins, but we should not provide abstract models nor traits. 
The user should not extend their models from this bundle, but instead create their own (we could also deprecate our interfaces to use the ones from the libraries).
```markdown
- `Sonata\TranslationBundle\Model\Gedmo\AbstractPersonalTranslatable` class
- `Sonata\TranslationBundle\Model\Gedmo\AbstractPersonalTranslation` class
- `Sonata\TranslationBundle\Model\Gedmo\AbstractTranslatable` class
- `Sonata\TranslationBundle\Model\AbstractTranslatable` class
- `Sonata\TranslationBundle\Traits\Gedmo\PersonalTranslatableTrait` trait
- `Sonata\TranslationBundle\Traits\Gedmo\TranslatableTrait` trait
- …
```
=> Deprecate abstract classes and traits for translatable models

src/Admin/Extension/AbstractTranslatableAdminExtension.php, src/DependencyInjection/Compiler/AdminExtensionCompilerPass.php, src/DependencyInjection/Compiler/GlobalVariablesCompilerPass.php, src/Filter/TranslationFieldFilter.php, src/Model/TranslatableInterface.php, src/Twig/Extension/SonataTranslationExtension.php, tests/Admin/Extension/AbstractTranslatableAdminExtensionTest.php, tests/Fixtures/Model/Knplabs/TranslatableEntity.php, tests/Fixtures/Model/ModelTranslatable.php
I think with these changes we can release a RC.
~I was thinking about deprecating the abstract classes from https://github.com/sonata-project/SonataTranslationBundle/tree/master/src/Model since I don't think users should extend their models from this bundle, in any case these models should be provided by the library (this can be also deprecated in `3.x`).~ Done in https://github.com/sonata-project/SonataTranslationBundle/pull/537
I am targeting this branch, because removing method is BC break.
```markdown
- Changed compiler passes as internal
- AbstractTranslatableAdminExtension is now `@internal`
```
=> Make compiler passes internal and minor tweaks
